# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'lalamove-test-ios' do

  use_frameworks!

  pod 'StakkKit', '~>1.4.0'
  pod 'GoogleMaps', '~>2.3.1'

end
